---
name: Continuous delivery
on:
  push:
    branches-ignore:
      - '**'
    tags:
      - 'v*'

jobs:
  test:
    name: Test and build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12'
      - uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - uses: ankane/setup-mariadb@v1
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npm test -- --coverage
      - name: Build the packages
        run: npm run build
      - name: Store artifacts
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: |
            dist/
            packages/djorm-docs/build

  publish-npm:
    name: Publish npm packages
    runs-on: ubuntu-latest
    needs:
      - test
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '13'
          registry-url: 'https://registry.npmjs.org'
      - uses: actions/download-artifact@v2
        with:
          name: dist
      - name: Install dependencies
        run: npm ci
      - name: Publish npm packages
        run: lerna publish from-package --yes
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_KEY }}

  publish-docs:
    name: Publish docs
    runs-on: ubuntu-latest
    needs:
      - test
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          name: dist
      - uses: JamesIves/github-pages-deploy-action@4.1.3
        with:
          branch: gh-pages
          folder: packages/djorm-docs/build
